version: '3.3'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'ecommerce'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'Ecommerce@2024'
      MYSQL_ROOT_PASSWORD: 'Ecommerce@2024'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - my-db:/var/lib/mysql
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
volumes:
  my-db: